name: 'Build Mongoose OS firmware V2'
description: 'Builds Mongoose OS firmware for a given target'
author: 'dea82, yaourdt, goleksiak'
inputs:
  mos-yml-path:
    description: 'Path to mos.yml file'
    required: false
    default: '.'
  platform:
    description: 'Target platform for this build'
    required: false
    default: 'esp32'
  build-args:
    description: 'Further build arguments (eg. --build-var ...)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--mos-yml-path'
    - ${{ inputs.mos-yml-path }}
    - 'build'
    - '--verbose'
    - '--platform'
    - ${{ inputs.platform }}
    - ${{ inputs.build-args }}
branding:
  icon: 'cpu'
  color: 'green'
